module.exports = {
    'en': {
        translation: {
            SKILL_NAME: 'Speedy Mathematician',
            WELCOME: 'Welcome to Speedy Mathematician. Are you the Einstein of Mathematics? Lets find out! ',
            READY: 'Are you ready to play?',
            REPEAT: 'Please say that again?',
            HELP: 'I will ask you a Mathematics question.If you get it right, you win a point.Do you want to start the game?',
            PLAYERS_NUMBER: "<say-as interpret-as='interjection'>Awesome!</say-as> Tell me how many players are playing.",
            START_GAME: "<say-as interpret-as='interjection'>All righty!</say-as> Let's get started!",
            SQUARE: "SQUARE ME! In this round I will speak a number. Reply quickly with the square of that number. Do you need me to explain you how to find the square of a number?",
            SQUARE_EXPLAIN: "To find the square of a number you have to multiply the number by itself. For example 3 times 3 = 9 <break strength='weak'/> or 12 times 12 is 144. To win a point reply quickly with the square of the given number. Are you ready to begin?",
            EXPLAIN_AGAIN: "Do you want me to explain it to you again?",
            GOODBYE: "Thanks for playing Speedy Mathematician. Goodbye.",
            CORRECT: "<say-as interpret-as='interjection'> %s!</say-as> %d is correct! ",
            WRONG: "<say-as interpret-as='interjection'> %s!</say-as> %d is incorrect. <s>The square of %d is %d. </s> ",
            QUESTION: "Question %d for Player %d. <s>What is the square of %d?</s> ",
            ROUND_COMPLETED: "Round %d Completed! The score is ",
            POINTS: "<s>%d points to player %d. </s>",
            NEXT_ROUND: "Are you ready for round %d?",
            GAME_FINISHED_WINNER: "GAME OVER! The overall winner is Player %d. You are crowned a Speedy Mathematician! Congratulations! <s> Do you wish to play again? </s>",
            GAME_FINISHED_DRAW: "GAME OVER! The overall winners are players %s. Ya'll are crowned Speedy Mathematicians! Congratulations! <s> Do you wish to play again? </s>",
            BEGIN_GAME: "<say-as interpret-as='interjection'> Cool! </say-as> Here we go then. ",
            SINGLE_WINNER: "The round goes to Player %d with a total points of %d. ",
            DRAW: "This round goes to Players %s with a total points of %d each. ",
            FACTORIAL: "FACT-O-BEE! Let's test how good you are at factorials. I'm gonna give you a number and you will tell me its factorial! Do you need me to explain you how to find the factorial of a number?",
            TRUEFALSE: "CATCH THE LIE! I have a couple of mathematical statements to make. Some are true, some are false. Point them out, and I take you up the leaderboard. Do I need to tell you how to go about this?",
            QUESTION_FACORIAL: "Question %d for Player %d. <s>What is the factorial of %d?</s> ",
            WRONG_FACTORIAL: "<say-as interpret-as='interjection'> %s!</say-as> %d is incorrect. <s>The factorial of %d is %d. </s> ",
            MODULO: "MODULO MAESTRO! In this round I will ask you the remainder of a modular operation! Do the math quick, and give me the correct answer. Do you want me to explain how to carry out a modulo operation?",
            QUESTION_MODULO: "Question %d for Player %d. <s>What is the remainder of %d modulo %d</s> ",
            WRONG_FACTORIAL: "<say-as interpret-as='interjection'> %s!</say-as> %d is incorrect. <s>The remainder of %s is %d. </s> ",
        }
    }
};